Repository team-peekabook/Peekabook-server, pull requests merged in 2023-04, with the labels that each got.

#169 #168 [Fix] 카카오 소셜 로그인 시, 버그 수정
  src/controller/authController.ts
  src/service/authService.ts
Labels: fix, 예슬🐼

#170 #165 [Feat] post - check user nickname
  src/constants/responseMessage.ts
  src/constants/userTokenCheck.ts
  src/controller/index.ts
  src/controller/userController.ts
  src/interfaces/user/UserDuplicateDTO.ts
  src/router/index.ts
  src/router/userRouter.ts
  src/service/userService.ts
  yarn.lock
Labels: feat, 현정🐸

#177 #172 [feat] fix user profile
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  src/config/s3Config.ts
  src/controller/mypageController.ts
  src/interfaces/mypage/patchUserRequestDTO.ts
  src/middlewares/index.ts
  src/middlewares/upload.ts
  src/router/mypageRouter.ts
  src/service/mypageService.ts
  yarn.lock
Labels: feat, 현정🐸

#175 #173 [Feat] 토큰 만료 시, 토큰 재발급 구현
  src/constants/responseMessage.ts
  src/controller/authController.ts
  src/modules/jwtHandler.ts
  src/router/authRouter.ts
  src/service/authService.ts
  src/service/userService.ts
Labels: feat, 예슬🐼

#179 #178 [feat] get user data
  src/constants/responseMessage.ts
  src/controller/mypageController.ts
  src/interfaces/user/IntroDTO.ts
  src/router/mypageRouter.ts
  src/service/userService.ts
Labels: feat, 현정🐸

#180 #176 [Feat] 소셜 애플 로그인 구현
  src/controller/authController.ts
  src/modules/social.ts
  src/service/authService.ts
Labels: feat, 예슬🐼

#183 #174 [Feat] 친구 차단하기
  src/constants/responseMessage.ts
  src/controller/friendController.ts
  src/middlewares/auth.ts
  src/modules/jwtHandler.ts
  src/router/friendRouter.ts
  src/service/friendService.ts
  test/friend.spec.ts
Labels: feat, 예슬🐼

#188 #188 [refactor] auth 수정
  src/controller/alarmController.ts
  src/controller/friendController.ts
  src/controller/mypageController.ts
  src/controller/pickController.ts
  src/controller/recommendController.ts
  src/controller/userController.ts
  src/router/alarmRouter.ts
  src/router/friendRouter.ts
  src/router/mypageRouter.ts
  src/router/pickRouter.ts
  src/router/recommendRouter.ts
  test/alarm.spec.ts
  test/friend.spec.ts
  test/pick.spec.ts
  test/recommend.spec.ts
Labels: refactor, 현정🐸

#189 #187 [Refactor] auth accesstoken
  src/controller/bookshelfController.ts
  src/controller/friendController.ts
  src/router/bookshelfRouter.ts
  src/router/friendRouter.ts
  src/router/recommendRouter.ts
  test/bookshelf.spec.ts
  test/friend.spec.ts
Labels: refactor, 예슬🐼

#191 #190 [Add] 회원 가입 시, 프로필 이미지 등록
  .github/workflows/deploy.yml
  package.json
  src/controller/authController.ts
  src/router/authRouter.ts
  src/service/authService.ts
  yarn.lock
Labels: add, 예슬🐼

#195 #193 [Fix] 사용자가 자신의 닉네임으로 사용자 검색 시, 안되도록 수정
  prisma/schema.prisma
  src/service/friendService.ts
Labels: fix, 예슬🐼

#196 #194 [Refactor] 글을 입력하는 모든 칸에서, 줄바꿈 제거 데이터 전처리
  src/controller/bookshelfController.ts
  src/controller/friendController.ts
  src/controller/mypageController.ts
Labels: refactor, 예슬🐼

#198 #197 [Fix] patch user
  src/router/mypageRouter.ts
Labels: fix, 현정🐸

#200 #199 [Fix] 닉네임에 공백 제거
  src/controller/authController.ts
  src/controller/mypageController.ts
Labels: fix, 예슬🐼

#202 #201 [Fix] 닉네임 중복 검사 시, 공백 제거 후 검사
  src/controller/userController.ts
Labels: fix, 예슬🐼
