Repository team-peekabook/Peekabook-server, pull requests merged in 2023-01, with the labels that each got.

#2 #1 [Setting] 프로젝트 세팅
  nodemon.json
  package.json
  prisma/schema.prisma
  src/config/index.ts
  src/constants/index.ts
  src/constants/response.ts
  src/constants/responseMessage.ts
  src/constants/statusCode.ts
  src/constants/tokenType.ts
  src/index.ts
  tsconfig.json
  yarn.lock
Labels: setting, 현정🐸

#4 #3 [setting] RDS와 prisma 연동
  prisma/schema.prisma
Labels: setting, 예슬🐼

#11 Feat/#5 friend recommend post api
  prisma/schema.prisma
  src/constants/responseMessage.ts
  src/controller/friendController.ts
  src/controller/index.ts
  src/index.ts
  src/interfaces/friend/FriendRecommendRequestDTO.ts
  src/router/friendRouter.ts
  src/router/index.ts
  src/service/friendService.ts
  src/service/index.ts
Labels: feat, 현정🐸

#14 #5 [Fix] service - 추천한사람, 추천받은사람 수정
  src/service/friendService.ts
Labels: fix, 현정🐸

#13 Feature/#8 bookshelf detail get api
  src/constants/responseMessage.ts
  src/controller/bookshelfController.ts
  src/router/bookshelfRouter.ts
  src/service/bookshelfService.ts
Labels: feat, 예슬🐼

#12 Feature/#7 bookshelf post api
  prisma/schema.prisma
  src/constants/responseMessage.ts
  src/controller/bookshelfController.ts
  src/controller/index.ts
  src/interfaces/bookshelf/BookshelfCreateDTO.ts
  src/router/bookshelfRouter.ts
  src/router/index.ts
  src/service/bookshelfService.ts
  src/service/index.ts
Labels: feat, 예슬🐼

#16 #6[feat] Get recommend book api
  prisma/schema.prisma
  src/constants/responseMessage.ts
  src/controller/index.ts
  src/controller/recommendController.ts
  src/router/index.ts
  src/router/recommendRouter.ts
  src/service/friendService.ts
  src/service/index.ts
  src/service/recommendService.ts
Labels: feat, 현정🐸

#20 #18 [Feat] user search api 구현
  src/constants/responseMessage.ts
  src/controller/friendController.ts
  src/router/friendRouter.ts
  src/service/friendService.ts
Labels: feat, 현정🐸

#22 #18 [Fix] 검색 키워드 모두 포함해야 조회하도록 수정
  src/service/friendService.ts
Labels: fix, 현정🐸

#23 #17 [Feat] bookshelf patch api
  prisma/schema.prisma
  src/constants/responseMessage.ts
  src/controller/bookshelfController.ts
  src/controller/index.ts
  src/interfaces/bookshelf/BookshelfUpdateDTO.ts
  src/router/bookshelfRouter.ts
  src/service/bookshelfService.ts
Labels: feat, 예슬🐼

#26 #19 [Feat] post follow api
  src/constants/responseMessage.ts
  src/controller/friendController.ts
  src/router/friendRouter.ts
  src/service/friendService.ts
Labels: feat, 현정🐸

#31 #29 [Feat] get book api
  src/constants/responseMessage.ts
  src/controller/pickController.ts
  src/router/pickRouter.ts
  src/service/pickService.ts
Labels: feat, 현정🐸

#34 #33 [Fix] model bookshelf의 createdAt 필드 타입 변경
  prisma/schema.prisma
  src/service/bookshelfService.ts
Labels: fix, 예슬🐼

#37 #36 [Feat] friend delete api
  prisma/schema.prisma
  src/constants/responseMessage.ts
  src/controller/friendController.ts
  src/router/friendRouter.ts
  src/service/friendService.ts
Labels: feat, 예슬🐼

#39 #38 [Feat] 나를 팔로우하는 친구들에게 알림 보내기 구현 완료
  prisma/schema.prisma
  src/service/bookshelfService.ts
Labels: feat, 예슬🐼

#40 #30 [Feat] get alarm api
  package-lock.json
  package.json
  prisma/schema.prisma
  src/constants/responseMessage.ts
  src/controller/alarmController.ts
  src/controller/index.ts
  src/interfaces/alarm/AlarmResponseDTO.ts
  src/router/alarmRouter.ts
  src/router/index.ts
  src/service/alarmService.ts
  src/service/index.ts
  yarn.lock
Labels: feat, 현정🐸

#45 #44 [Feat] 책 추천 알림 추가하기
  src/service/friendService.ts
Labels: feat, 예슬🐼

#43 #42 [Feat] 팔로우 알림 추가하기 구현 완료
  src/service/friendService.ts
Labels: feat, 예슬🐼

#46 #41 [Fix] recommend
  src/interfaces/recommend/RecommendGetDTO.ts
  src/router/recommendRouter.ts
  src/service/recommendService.ts
Labels: fix, 현정🐸

#49 #48 [Fix] UserDTO import문 오타 수정
  prisma/schema.prisma
  src/interfaces/bookshelf/FriendBookshelfResDTO.ts
  src/interfaces/bookshelf/MyBookshelfResDTO.ts
  src/service/bookshelfService.ts
  src/service/userService.ts
Labels: fix, 예슬🐼

#50 #47 [Fix] fix deploy error
  src/interfaces/friend/FriendRecommendRequestDTO.ts
  src/service/friendService.ts
Labels: fix, 현정🐸

#52 #51 [Fix] fix search friend
  src/controller/friendController.ts
  src/interfaces/friend/SearchFriendResponseDTO.ts
  src/service/friendService.ts
Labels: fix, 현정🐸

#53 [Add] slack webhook API 추가
  package-lock.json
  package.json
  src/constants/responseMessage.ts
  src/controller/friendController.ts
  src/controller/pickController.ts
  src/interfaces/friend/FriendRecommendRequestDTO.ts
  src/modules/slackErrorMessage.ts
  src/modules/slackWebhook.ts
  src/service/friendService.ts
  yarn.lock
Labels: feat, 현정🐸

#57 [feat] slack webhook api
  src/controller/pickController.ts
Labels: feat, 현정🐸

#55 [Add] husky 관련 file 추가
  .husky/pre-commit
  package-lock.json
  package.json
  src/controller/bookshelfController.ts
  yarn.lock
Labels: add, 예슬🐼

#59 [Fix] friendService 오타 수정
  src/service/friendService.ts
Labels: fix, 현정🐸

#63 #54 [Add] add husky file
  .husky/pre-commit
  package-lock.json
  src/controller/bookshelfController.ts
Labels: add, 예슬🐼

#64 #62 [Add] mocha 테스트 환경 세팅
  .husky/pre-commit
  package-lock.json
  package.json
  test/alarm.spec.ts
  test/bookshelf.spec.ts
  test/friend.spec.ts
  test/pick.spec.ts
  test/recommend.spec.ts
  yarn.lock
Labels: add, 예슬🐼

#66 #65 [Recactor] post recommend
  .husky/pre-commit
  src/constants/responseMessage.ts
  src/controller/friendController.ts
  src/service/friendService.ts
  yarn.lock
Labels: refactor, 현정🐸

#69 #67 [refactor] response message 수정
  src/controller/friendController.ts
Labels: add, 현정🐸

#73 #71 [Refactor] bookshelf get api
  src/controller/bookshelfController.ts
  src/service/bookshelfService.ts
Labels: refactor, 예슬🐼

#76 #72 [Refactor] api response 수정
  src/constants/responseMessage.ts
  src/controller/friendController.ts
  src/service/friendService.ts
  src/service/pickService.ts
Labels: refactor, 현정🐸

#77 #70 [Refactor] bookshelfId 값도 response body에 추가
  src/interfaces/book/BookDTO.ts
  src/service/bookshelfService.ts
Labels: refactor, 예슬🐼

#79 #78 [Add] recommend api
  src/service/recommendService.ts
Labels: add, 현정🐸

#80 #75 [Refactor] 책 상세 정보 조회 API refactoring
  src/controller/bookshelfController.ts
  src/service/bookshelfService.ts
Labels: refactor, 예슬🐼

#82 #81 [Fix] 친구 목록 정렬
  src/service/bookshelfService.ts
Labels: fix, 예슬🐼

#85 Add/#84 request response data
  src/controller/pickController.ts
  src/service/pickService.ts
Labels: add, 현정🐸

#88 #87 [Add] user header
  src/controller/alarmController.ts
  src/controller/bookshelfController.ts
  src/controller/friendController.ts
  src/controller/pickController.ts
  src/controller/recommendController.ts
Labels: add, 현정🐸

#89 #83 [Refactor] 등록한 책 삭제 리팩토링
  src/controller/bookshelfController.ts
  src/service/bookshelfService.ts
Labels: refactor, 예슬🐼

#91 #90 [Add] request header 에서 유저 아이디 받는 코드 추가
  src/controller/bookshelfController.ts
  src/service/bookshelfService.ts
Labels: add, 예슬🐼

#92 Add/#87 user header
  src/controller/alarmController.ts
  src/controller/friendController.ts
  src/controller/pickController.ts
  src/controller/recommendController.ts
  src/service/alarmService.ts
  src/service/bookshelfService.ts
  src/service/friendService.ts
Labels: add, 현정🐸

#94 Add/#87 user header
  src/controller/alarmController.ts
  src/controller/friendController.ts
  src/controller/pickController.ts
  src/controller/recommendController.ts
  src/service/bookshelfService.ts
  src/service/friendService.ts
  src/service/pickService.ts
  src/service/recommendService.ts
Labels: add, 현정🐸

#99 #98 [Fix] recommend 최신순
  src/controller/pickController.ts
  src/service/recommendService.ts
Labels: fix, 현정🐸

#100 #95 [Test] friend test
  package-lock.json
  package.json
  src/index.ts
  test/friend.spec.ts
  yarn.lock
Labels: 현정🐸, test

#108 #95 [Test] friend test 형식수정
  test/friend.spec.ts
Labels: 현정🐸, test

#107 #102 [Test] 책 상세 정보 조회 API 테스트 코드
  test/bookshelf.spec.ts
Labels: 예슬🐼, test

#113 #112 [Fix] pick 수정
  src/service/pickService.ts
Labels: fix, 현정🐸

#114 #109 [Test] recommend test
  test/recommend.spec.ts
Labels: 현정🐸, test

#115 #109 [Fix] pick최신순
  src/service/pickService.ts
  test/friend.spec.ts
  test/recommend.spec.ts
Labels: fix, 현정🐸

#116 #103 [Test] bookshelf - 책 삭제 API 테스트 코드
  src/service/bookshelfService.ts
  test/bookshelf.spec.ts
Labels: 예슬🐼, test

#119 #97 [Test] bookshelf test
  test/bookshelf.spec.ts
Labels: 예슬🐼, test

#118 Test/#111 alarm
  test/friend.spec.ts
Labels: add, 현정🐸

#120 #111 [Test] alarm test
  test/alarm.spec.ts
Labels: 현정🐸, test

#121 [Test] 등록한 책 상세 조회 API 테스트 코드
  test/bookshelf.spec.ts
Labels: 예슬🐼, test

#122 #103 [Test] 등록한 책 삭제 after 로직 추가
  test/bookshelf.spec.ts
Labels: 예슬🐼, test

#123 #104 [Test] 등록한 책 수정 테스트 코드
  test/bookshelf.spec.ts
Labels: 예슬🐼, test

#125 #105 [Test] 내 책장 조회하기 테스트 코드
  test/bookshelf.spec.ts
Labels: 예슬🐼, test

#126 #110 pick test
  test/pick.spec.ts
Labels: 현정🐸, test

#130 #110 [Test] pick patch 수정
  test/bookshelf.spec.ts
  test/pick.spec.ts
Labels: add, 현정🐸

#132 #110 pick patch 수정
  test/bookshelf.spec.ts
Labels: add, 현정🐸

#135 #133 [Fix] bookshelfid로 path param 변경
  src/controller/bookshelfController.ts
  src/router/bookshelfRouter.ts
  src/service/bookshelfService.ts
Labels: fix, 예슬🐼

#136 #133 [Fix] 정렬 기준 수정
  src/service/bookshelfService.ts
Labels: fix, 예슬🐼

#138 #137 [Fix] path param명 수정
  src/controller/bookshelfController.ts
  src/service/bookshelfService.ts
Labels: fix, 예슬🐼

#139 [Test] bookshelf 테스트 코드 작성
  test/bookshelf.spec.ts
Labels: 예슬🐼, test

#140 [Chore] husky pre-commit 세팅
  .husky/pre-commit
  package.json
Labels: chore, 예슬🐼

#144 #141 [Add] 대소문자 코드 수정
  src/service/friendService.ts
  test/friend.spec.ts
Labels: add, 현정🐸

#143 #142 [Fix] 책장 전체 조회 시 정렬 기준 수정
  src/service/bookshelfService.ts
Labels: fix, 예슬🐼

#146 #145 [Fix] pick한 책 삭제 시, 나머지 pick한 책 순위 변경
  src/service/bookshelfService.ts
Labels: fix, 예슬🐼
