Repository team-peekabook/Peekabook-server, pull requests merged in 2023-03, with the labels that each got.

#149 #148 [Refactor] 책장 service에서 friend 관련 service 분리
  prisma/schema.prisma
  src/service/bookshelfService.ts
  src/service/friendService.ts
Labels: refactor, 예슬🐼

#151 [Refactor] 친구 책장 조회 api
  .github/workflows/deploy.yml
  package.json
  scripts/after-deploy.sh
  src/service/bookshelfService.ts
  src/service/friendService.ts
  src/service/userService.ts
Labels: refactor, 예슬🐼

#153 [Refactor] 내 책장 조회 api user 관련 서비스 분리
  src/service/bookshelfService.ts
Labels: refactor, 예슬🐼

#157 [Fix] user 테이블 updatedAt 컬럼 추가 시, prisma 파일 수정
  prisma/schema.prisma
Labels: fix, 예슬🐼

#158 [refactor] fix pick code
  src/controller/pickController.ts
Labels: refactor, 현정🐸

#161 [Feat] 책 등록 시, 출판사 컬럼까지 저장
  prisma/schema.prisma
  src/interfaces/bookshelf/BookshelfCreateDTO.ts
  src/interfaces/friend/FriendRecommendRequestDTO.ts
  src/service/alarmService.ts
  src/service/bookService.ts
  src/service/bookshelfService.ts
  src/service/friendService.ts
  src/service/userService.ts
  test/bookshelf.spec.ts
  test/pick.spec.ts
Labels: feat, 예슬🐼

#162 #160 [Feat] post report
  .github/workflows/deploy.yml
  .vscode/settings.json
  package-lock.json
  package.json
  prisma/schema.prisma
  src/config/index.ts
  src/constants/responseMessage.ts
  src/controller/friendController.ts
  src/interfaces/friend/FriendReportRequestDTO.ts
  src/interfaces/friend/ReportMailRequestDTO.ts
  src/interfaces/friend/reportMailDTO.ts
  src/modules/mail.ts
  src/modules/reportMessage.ts
  src/router/friendRouter.ts
  src/service/friendService.ts
  test/friend.spec.ts
  test/pick.spec.ts
  yarn.lock
Labels: feat, 현정🐸

#164 #160 [feat] test code fix
  test/friend.spec.ts
Labels: fix, 현정🐸

#167 #163 [Feat] 카카오 소셜 로그인 및 회원가입 구현
  .github/workflows/deploy.yml
  package-lock.json
  package.json
  prisma/schema.prisma
  src/controller/alarmController.ts
  src/controller/authController.ts
  src/controller/bookshelfController.ts
  src/controller/friendController.ts
  src/controller/pickController.ts
  src/controller/recommendController.ts
  src/interfaces/alarm/AlarmResponseDTO.ts
  src/interfaces/auth/SignUpReqDTO.ts
  src/interfaces/user/UserDTO.ts
  src/middlewares/auth.ts
  src/middlewares/index.ts
  src/modules/jwtHandler.ts
  src/modules/slackErrorMessage.ts
  src/modules/social.ts
  src/router/authRouter.ts
  src/router/index.ts
  src/service/authService.ts
  src/service/index.ts
  test/pick.spec.ts
  yarn.lock
Labels: feat, 예슬🐼
