Repository team-peekabook/Peekabook-server, pull requests merged in 2023-06, with the labels that each got.

#215 #214 [refactor] code fix
  src/constants/responseMessage.ts
  src/controller/friendController.ts
  src/service/friendService.ts
  test/friend.spec.ts
Labels: refactor, 현정🐸

#216 #213 [Refactor] 예슬 담당 api response body 리팩토링
  src/constants/responseMessage.ts
  src/controller/authController.ts
  src/controller/bookshelfController.ts
  src/controller/friendController.ts
  src/controller/mypageController.ts
  src/middlewares/auth.ts
  src/service/authService.ts
  src/service/friendService.ts
Labels: refactor, 예슬🐼

#220 #219 [FIX] 차단한 유저 검색이 안되도록 로직 수정
  src/service/friendService.ts
Labels: fix, 예슬🐼

#222 #221 [fix] alarm fix
  .vscode/settings.json
  src/service/alarmService.ts
  src/service/bookshelfService.ts
Labels: fix, 현정🐸
