Repository team-peekabook/Peekabook-server, pull requests merged in 2023-10, with the labels that each got.

#228 [Fix] #227 팔로우한 친구 목록 조회 시, 최근에 팔로우한 순으로 정렬
  src/service/friendService.ts
Labels: fix, 예슬🐼

#230 #229 [feat] 버전 조회하기
  package.json
  prisma/schema.prisma
  src/constants/responseMessage.ts
  src/controller/userController.ts
  src/index.ts
  src/router/userRouter.ts
  src/service/userService.ts
  yarn.lock
Labels: feat

#231 #229 [feat] version add
  src/index.ts
Labels: fix, 현정🐸
